[package]
name = "starklotto_adapter_vrf"
version = "0.1.0"
edition = "2023_10"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.9.2"
cartridge_vrf = { git = "https://github.com/cartridge-gg/vrf.git" }
openzeppelin_access = "0.18.0"
openzeppelin_token = "0.18.0"

[dev-dependencies]
openzeppelin_testing = "0.18.0"
openzeppelin_utils = "0.18.0"
# vlf
snforge_std = "0.31.0"

[[target.starknet-contract]]
casm = true # taggle this to `false` to speed up compilation/script tests
allowed-libfuncs-list.name = "experimental"

[tool.scarb]
allow-prebuilt-plugins = [
	"snforge_std",
] # Avoids the need to install Rust for snforge_std/starknet-foundry

[tool.fmt]
sort-module-level-items = true

[[tool.snforge.fork]]
name = "SEPOLIA_LATEST"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_8"
block_id.tag = "latest"

